name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "MONDAY_API_KEY=${{ secrets.MONDAY_API_KEY }}" >> .env
        echo "GOOGLE_SHEET_NAME=${{ secrets.GOOGLE_SHEET_NAME }}" >> .env
        echo "GRAB_USERNAME=${{ secrets.GRAB_USERNAME }}" >> .env
        echo "GRAB_PASSWORD=${{ secrets.GRAB_PASSWORD }}" >> .env
        echo "SHOPEE_USERNAME=${{ secrets.SHOPEE_USERNAME }}" >> .env
        echo "SHOPEE_PASSWORD=${{ secrets.SHOPEE_PASSWORD }}" >> .env
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.py

    - name: Run tests with pytest
      run: |
        pytest
